name: erc20indexer
description: ERC-20 indexer
networks:
  - id: 31337
    start_block: 0
    rpc_config:
      url: "http://127.0.0.1:8545"
    contracts:
      - name: TradePair
        address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
        handler: src/EventHandlers.ts
        abi_file_path: "abi/TradePair.json"
        events:
          - event: PositionOpened
            requiredEntities:
              - name: User
              - name: Position
          - event: PositionClosed
            requiredEntities:
              - name: User
              - name: Position
