name: PeppyIndexer
description: PeppyIndexer
networks:
  - id: 1073
    start_block: 678356
    rpc_config:
      url: "https://json-rpc.evm.testnet.shimmer.network"
    contracts:
      - name: TradePair
        address: ["0xAf4580decb30B4Cb06dac700cF27CD1c9ce4b1FD","0x2DbD1b34b66CC372e34E1bDD00C65e7109E195E3","0x6Ef16cBbD8a8D0575C426bC3cb621e2cb509c764"]
        handler: src/EventHandlers.ts
        abi_file_path: "abi/TradePair.json"
        events:
          - event: PositionOpened
            requiredEntities:
              - name: User
              - name: Position
          - event: PositionClosed
            requiredEntities:
              - name: User
              - name: Position
          - event: TradePairConstructed
            requiredEntities:
              - name: TradePair